version: '2'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
  broker_app:
    image: dius/pact-broker:2.4.0-1
    ports:
      - "80:80"
    links:
      - postgres
    environment:
      - PACT_BROKER_DATABASE_USERNAME=postgres
      - PACT_BROKER_DATABASE_PASSWORD=password
      - PACT_BROKER_DATABASE_HOST=postgres
      - PACT_BROKER_DATABASE_NAME=postgres
      - PACT_BROKER_BASIC_AUTH_USERNAME=pact
      - PACT_BROKER_BASIC_AUTH_PASSWORD=broker
      

